name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: docker://golangci/golangci-lint:v1.23.8
  #       with:
  #         args: golangci-lint run
  #       env:
  #         CGO_ENABLED: 0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
        env:
          RUNNER_TEMP: /tmp
      - uses: actions/checkout@v2
      - run: make test

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      # - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}